### ISSUE TITLE
Commodore 64 5.25" floppy imaging to d64 - Problem with B side of disk

### ISSUE THREAD

**Issue by hpingel** [davidgiven/fluxengine#111]
Hi David,

Today I got my 5.25" TEAC drive - and it works! I was already able to create two d64 images that work in VICE emulator. I had some retries in the upper track number > 70 but I wasn't sure if that is a problem at all. (I haven't got around to do a d64 hash validation via writing d64 to disk via real 1541 floppy drive and then reading disk with Fluxengine).

I'm currently having an issue with the B-sides of the floppy disks where Fluxengine stops reading attempts at the very start. It seems that only B-sides are affected:

```
$ time ./fluxengine read c64 -o brucelee.d64
Reading from: :d=0:s=0:t=0-79x2
  0.0: Error: data transfer failed: Pipe error

real	0m3,242s
user	0m0,000s
sys	0m0,011s
```

Do you have any advice if I'm doing something wrong? I turn the disk in the drive before I want to read the B-side. Is there a 4-track offset?

**Comment by davidgiven** [comment]
Excellent news.

> Do you have any advice if I'm doing something wrong? I turn the disk in the drive before I want to read the B-side. Is there a 4-track offset?

These are flippy disks, right? With a notch each side, and you insert the disk upside down to access the other side? In order to make these work, you need a specially modified drive. See the 'flippy disk' question here for more information: http://cowlark.com/fluxengine/doc/faq.html

There's various types of modification which can be done, but I have no experience with any of them and so can't advise. I was hoping to find someone who had and pick their brains.

**Comment by hpingel** [comment]
Hi David,

As you indicated it turns out the floppy drive needs a hardware mod for reading 1541 B-sides (although 1541 disks are no flippy disks as such).

To promote your project I did a little video and posted it here:
https://www.forum64.de/index.php?thread/94408-fluxengine-in-action-d64-image-erzeugen-mit-pc-floppy-drive-video/

**Comment by hpingel** [comment]
Hi David,

Can Fluxengine read the data backwards (a workaround that you indicated in your FAQs regarding Flippy disks)? Is there a parameter to reverse the bitstream?

**Comment by davidgiven** [comment]
There's no theoretical reason why not, but there's no code to do it because it hasn't come up yet. The internal representation is a series of intervals and events so actually reversing the signal is easy. Note, however, that reading the back of a flippy disk with a modern drive is _much_ harder than modifying the drive to allow you to insert flipped disks. Modern drives have an offset between the two heads --- track 0 is in a physically different place on the back. But a flippy disk, of course, writes track 0 with the A side head on both sides, because you turn the disk over, which means that some of the tracks aren't accessible on a modern drive. You need either a more serious hardware mod to let the head move out of bounds or you physically adjust the position of the head. I'd imagine that flipping the disk and doing the index signal mod is easier.

I've never used a 1541, so just to check my knowledge: the 1541 was a single-sided drive which required you to insert disks upside down to get at the back, right?

**Comment by hpingel** [comment]
You are right about the 1541 (single-sided) and also right about the track offset. On the forum64 thread linked above the discussion today has circulated around the same issues you mention.

A kind person refered to this tutorial:
https://forum.classic-computing.de/forum/index.php?thread/16875-kryoflux-modifikation-eines-teac-fd-55gfr-5-25-hd-diskettenlaufwerks-f%C3%BCr-flippy/

The tutorial explains how to cheat with the index pulse to allow the B-side of the flippy disk be read when the disk is inserted upside-down in the PC drive.

Problem is: There is no demand - as most C64 enthusiasts possess the 1541 drive and can connect the 1541 drive to the PC via mocrocontroller (xum1541, Zoomfloppy). So to modify a PC drive is nothing the community really needs. It's more of a tinkering project of a single enthusiast.

**Comment by stynxx** [comment]
The main problem of flippy-disks seem to be the missing index-signal if the disk is flipped. I have no idea if the floppy drive needs the index-signal to work normally but maybe a separate sync sensor on the drive motor could help to always have a sync signal? There are some hall sensors that go low (like the index-signal), if a magnetic field is recognised. Replacing the index-signal with the output of the new sync sensor would maybe make some disks unreadable, since the index-hole is media-dependant and indicates the beginning of a track?

**Comment by davidgiven** [comment]
Most modern drives won't start emitting data until they see index pulses. I think they use them to detect whether the drive's spinning up to speed.

FluxEngine itself doesn't care about the index pulses, other than using them to count rotations, except for some exotic hard-sectored formats. So faking the pulses to spoof the drive is perfectly reasonable. See: #113

**Comment by stynxx** [comment]
> Most modern drives won't start emitting data until they see index pulses. I think they use them to detect whether the drive's spinning up to speed.
> 
> FluxEngine itself doesn't care about the index pulses, other than using them to count rotations, except for some exotic hard-sectored formats. So faking the pulses to spoof the drive is perfectly reasonable. See: #113

I have successful added a selectable 2nd index/sync sensor to a FD55. The method is closely related to the way it way described by the original [catweasel](https://web.archive.org/web/20060613190218/http://www.siliconsonic.de/t/flipside.html) website.(mentioned in #113 )
The Drive does work normally with that modification and does not need any software or firmware upgrade. Installation is a bit fiddly as the used reed-switch must be aligned 'correctly'.
