### ISSUE TITLE
Feature Request : Revolutions=1.0 / Splice 

### ISSUE THREAD

**Issue by ourIThome** [davidgiven/fluxengine#152]
This is a place holder, again lowest priority ... one for a sunny day.

Revolutions works brilliantly, letting me mass image some old disks ~ 1m08.

Because when a disk spins, you might start in the middle of sector 1, when you do a revolution of 1.0 you get sector 1 split between the start of the capture, and at the end of the capture.  Currently there is no splicing of the split sector.

I currently use a revolution of 1.1 so that I get another read of the problem sector ... and sometimes I get an extra 1 or 2.  This means the decoder has extra work to do decode sectors already read.

Would it be possible to allow a splicing of the end of the data read with the beginning part?  Might shave off another 4 seconds.

**Comment by davidgiven** [comment]
I'm going to have to close this one as Infeasible --- splicing is only possible if the disk format has special support for it. If we start reading in the middle of a sector, there is no way to know where we are, and which data is actually valid and which is just noise. This works on the Amiga because the format records this information, but AFAIK no other format supports it.
