### ISSUE TITLE
Building Client not possible 

### ISSUE THREAD

**Issue by Trekinfo** [davidgiven/fluxengine#384]
Hallo,

Since a few Days i try to build the Client but without success.

On 64bit Virtual Machines Debian und Ubuntu i got massive Errors while Compiling and had no success
Raspberry 4 (Bullseye) crashes during Compiling
Raspberry 2 (Buster) crashes
32bit Virtual Machine Debian (Bullseye) crashes also
Cygwin on Win10 also not work

I had only limitated Knowledge of Linux.
Why is it not possible to distribute a precompiled Version of Fluxengine for Users who are not familiar in the process of Compiling?

Greets Trekinfo

**Comment by davidgiven** [comment]
What errors are you getting? Please make sure you have all the dependencies installed from here: http://cowlark.com/fluxengine/doc/building.html#building-the-client

There is a Windows precompiled binary, but distributing precompiled versions for Linux is difficult because there are so many Linux variants.

**Comment by Trekinfo** [comment]
Oh,

if there is a Windows Version, then everything is fine.
I thought i must compile the Windows version on a Linux machine.

Greets Trekinfo

**Comment by davidgiven** [comment]
The Windows version, sadly, must be built on a Windows machine... anyway, good to know there's no problem. Closing. Please reopen if you have any other issues.
