### ISSUE TITLE
Images with bad sectors on source disk

### ISSUE THREAD

**Issue by hubertushirsch** [davidgiven/fluxengine#63]
Hello David,

http://cowlark.com/fluxengine/doc/disk-zilogmcz.html

Based on your website I have to say the following:

>> if a sector is received by the OS at all, it's guaranteed to be valid.

This is only true if the image was generated by a perfectly error free floppy disk.
Or produced synthetically.

The reason for my request:
Jon Hales from the Center of Computing History asked me for help with the analysis of Zilog RIO floppy disks.
He gave me some binary images that were created with your help.
I wrote a tool for him with which he can analyze these images at the file system level.
Including the extraction of files to the PC.
These images contain 128byte data + 4byte pointers (132byte/sector total) per sector.
No CRC.

Jon informed me that some disks are in poor condition and not all sectors could be read cleanly.

While writing and testing the tool, I found many sectors that contained only zeros
(132 zero bytes) even though they were part of regular files.
Since this can not logically occur on Zilog RIO,
I define these sectors as bad sectors in my tool and provide a synthetic CRC error.

In the deeper analysis of the file system on the floppy disks,
I found sectors that looked good at first glance,
but on closer examination contained data errors.
For example, Non-ASCII characters in text files
(text files in RIO are plain text files 7-bit ASCII)
or sectors with pointers pointing to addresses outside the disk geometry.
Bit or byte errors in binary files can not be easy
be recognized automatically or by looking through the eyes.

For this analysis work would be the control option through the original CRC field
important. I (and Jon) can not trust any file that we extract from the images.

Regards
Ralf
http://rio.early8bitz.de

**Comment by davidgiven** [comment]
So the problem is that knowing the CRC won't tell you if the sector data is valid or not. All the CRC does is let you know whether the data was written to and then read from the disk correctly. It doesn't tell you if the data actually makes sense or not. I have an MCZ disk image where the sector link fields are garbage, because the operating system that wrote the disk didn't (as far as I know) use them.

So even if you _did_ have the CRCs, it wouldn't actually help your tool. You'd still have to do robust testing of the filesystem structure in order to verify that the filesystem was valid and worked, and the only way to do that is through heuristics.

That said, it's a perfectly reasonable request to know when it's known that a sector is _definitely_ invalid, because it was read back incorrectly. Currently FluxEngine writes a log of which sectors were bad, but then outputs data even if the checksum failed, on the principle that anything's better than nothing, but that's not actually true. You should have received these logs with the disk images but they're not good for use programmatically.

I _don't_ want to put the checksum in the disk images, because for some formats the checksum depends on data which isn't in the image (i.e. sector metadata) and so cannot be tested or recreated by an application. But I also don't want to make the images more complex --- right now the simple array-of-sectors format can be read by anything. So I can't add an extra table to the format.

Instead I'll change things so that bad sectors are not written to the image unless explicitly asked for on the command line. That way it should at least be obvious when they're bad. I appreciate that's not very satisfactory, but should solve your immediate problems. Eventually I hope to move to a standard disk image format with more data in it, but I haven't found one yet and don't want to make my own.

**Comment by hubertushirsch** [comment]
Thank you very much for the comment.
I will answer in detail in the next few days.

**Comment by hubertushirsch** [comment]
Everything you write is correct. But it does not fit the use case of Jon.

The archiving of files from floppy disks requires the same knowledge of the file system,
regardless of whether you use the original system (hardware) or an image.
Assume that I have the necessary knowledge of RIO.
Logical errors that the OS made earlier are on a physical floppy disk and equally present in the image.
So that's not an issue that affects your engine.

The problem is the physical defects on the original disks.

You wrote:
The CRC is usually internal to the floppy disk subsystem and not exposed to code 
--- if a sector is received by the OS at all, it's guaranteed to be valid.
============

You forget:
The OS also receives information when reading the sector in the floppy subsystem
an error (eg CRC error) has occurred. Each OS has specific error codes,
who inform the calling program about the success or failure of an operation.

This information does not have an emulator or parser, every disk operation is successfully.
Even if the sector in the image comes from a bad sector in the original.

Ok - In emulators where you work in a well-known environment with "physically" clean images,
that is not a problem.

Analyzing diskettes based on the image of the disk that definitely has physical defects requires that I have information about each sector in the image,
whether or not it was correctly readable on the physical diskette.
Otherwise I have worse conditions when working with the images than if the original physical system were used.
I can imagine the following solutions:
The image contains all the bytes of the sector, including the CRC, and the analysis tool can recalculate the physical integrity of the sector.
- or-
The image does not contain the CRC, but the Flux File to Binary Image Conversion Tool checks the CRC of each sector and writes a log file in parallel.
This requires that you use the correct algorithm and know which bytes are included in the calculation and which are not.

You wrote:
I have an MCZ disk image where the sector link fields are garbage,
because the operating system that wrote the disk didn't (as far as I know) use them.
============

All sectors on a RIO floppy disk have the pointers in bytes 129..132 of the sector.
But only in the records of regular files are the pointers used
to link the Directory Entry, Descriptor Block (the metadata of the file) and the file's data records.
Regardless, formatting a floppy disk (RIO FORMAT utility) writes values to the pointer fields of each freshly formatted sector, which are definitely valid disk addresses (within disk geometry).
This can be read from the source code of the FORMAT utility.

You wrote:
Currently FluxEngine writes a log of which sectors were bad, ..........
You should have received these logs with the disk images but they're not good for use programmatically.
============

I only received the *.img files from Jon.
I'll ask him for the log files and see if that helps.

**Comment by hubertushirsch** [comment]
Jon sent me the log files to the images.
The Sector Matrix Good/Bad/Missing (./B/X) is well suited for my analysis. It can also be processed easily automated.
Thanks for the hint.

**Comment by davidgiven** [comment]
Sorry for the delay --- I've just pushed an update which adds basic support for writing LDBS files, as used by the libdsk tools. (See http://www.seasip.info/Unix/LibDsk/ldbs.html and http://www.seasip.info/Unix/LibDsk/.) These contain a checksum bit allowing you to identify whether the sector was read correctly.

Note that this does _not_ guarantee that the data was correct, just that it was stored to disk and read back correctly, which is not the same thing.
