### ISSUE TITLE
Docs about building the client should be expanded

### ISSUE THREAD

**Issue by leandrinux** [davidgiven/fluxengine#65]
Hi! 

I'm afraid I'm not that experienced building stuff with make, and I could use some directions in the process of building the client software. Currently it's just one paragraph. First I attempted compiling on an older mac with El Capitan, but it looks like this needed something newer. Then I attempted it with Mojave and it seems it worked, but after typing `make` I can't find any binaries anywhere. My intention is to move these binaries to the older machine to check out if this worked. Later I'd like to build this on Windows, but I have no idea how to even start.

I believe it would be handy to have tagged commits, so that Github interprets them as releases, and it would be cool if they also included precompiled binaries to give people the chance of skipping all this process.

**Comment by davidgiven** [comment]
The binaries are left in the `.obj` directory (this is actually documented; see http://cowlark.com/fluxengine/doc/using.html).

TBH, the FluxEngine tools are _not_ ready for production use --- they're very much rapidly hacked together. I don't want to produce releases because that implies they're tested, which they're not. Making binaries is also pretty hard and requires access to more hardware than I have, and are of questionable use anyway (which architectures? I do a lot of development on Linux ARM). Even with binaries, you have to be reasonably up to speed with tools like Cygwin to use them.

I live in fear of someone trying to make FluxEngine work, failing, and irrevocably destroying something unique. That disclaimer on the front page is there for a reason.

Incidentally, I believe you are the first person ever to have tried the FluxEngine tools on OSX. Did they work? Do you have the hardware?

**Comment by davidgiven** [comment]
Both the build system and the client have been drastically overhauled; this should be better now.
