### ISSUE TITLE
upgrade-flux-file tool doesn't upgrade Brother SQLite flux files

### ISSUE THREAD

**Issue by thorsted** [davidgiven/fluxengine#768]
I have a few older Brother typewriter disk flux files in the old SQLite format. When I run the upgrade-flux-file tool it produces a new flux file fine, but when I read the flux file in and output a Brother 240k image file, the file is empty.

**Comment by davidgiven** [comment]
That shouldn't happen. If you're original flux file doesn't contain anything confidential, could you zip and attach it so I can have a look?

**Comment by thorsted** [comment]
Sure thing.
[Uploading Tabs-HF.flux.zip…](SQLite Flux file)

**Comment by davidgiven** [comment]
Found it --- looks like the head bias is different. The documentation is stale, but adding `--drive.head_bias=0` does a clean read. I'll update the documentation. This is for compensating for misaligned drives. The default value for the head bias is 3, because that's what my machine's drive did, but I think it's now broken so maybe setting it to 0 might be better if more people's drives are like that.

For reference, the clue is in the output logs:

```
 3.0: 402 ms in 101632 bytes
      no more data; giving up
      48 raw records, 24 raw sectors; 3.95us clock (253kHz)
      sectors: 0.0.0? 0.0.1? 0.0.2? 0.0.3? 0.0.4? 0.0.5? 0.0.6? 0.0.7? 0.0.8? 0.0.9? 0.0.10? 0.0.11? 2.0.0 2.0.1 2.0.2 2.0.3 2.0.4 2.0.5 2.0.6 2.0.7 2.0.8 2.0.9 2.0.10 2.0.11
      3072 bytes decoded
```

The first 3.0 is the physical track it's on; the `0.0.0?` is indicating that it's looking for logical track 0, head 0, sector 0; the `2.0.0` means that it's _found_ sectors on logical track 2, head 0, sector 0, meaning that the tracks are in the wrong place.

I suspect what changed is that FluxEngine used to automatically try to compensate for this, but it now no longer does because it caused more problems than it fixed...

**Comment by davidgiven** [comment]
Correction: you need head_bias 1.

```
$ ./fluxengine ls brother --240 -f Tabs-HF.flux  --drive.head_bias=1
      OPTION: 240kB 3.5" 78-track SS GCR
 1.0: 401 ms in 101760 bytes
  TABS01         445 A    
  HEADFOOT       183 A    
(2 files, 628 bytes)
```
