### ISSUE TITLE
Brother 240k: super tough to read, is this an example of an alignment problem?

### ISSUE THREAD

**Issue by david-schmidt** [davidgiven/fluxengine#79]
Question for you regarding a Brother 240k disk I've got here.  I am able to scrape off a little good information from the disk, but the sector report looks really hairy.  Is it possible/likely that this is an example of a misaligned disk that would have required microstepping back in the day, do you think?

```
H.SS Tracks --->
0. 0 .?XXXXXBXXXB.XXXX..?.XXXXXXXBX..XXXXXXXXXBBXXXX.B?.XXXXXBXXXXXXXX.?.XX.BBBXXX.
0. 1 .?XXXXBXXXXBX?XXXX..XXXXBXXXXX..BXXXXXXXXX?BXXXX.?BBXXXXBXXXXXXXXXXXBXX.BBBXX.
0. 2 .?BXXX?BXXXX.XXXXB..BXXXXXXXBX..XXXX?XBXX.XXXXX.X..XXX?BXXXX?.XXXXB.XXXX.?XXX.
0. 3 .?XXXXXBXXXBXBXXXX...XXXXXXXX.B.XXXXXBXXXXX?XXXX.X.BXXXXXXXXXBXXXXXX.X....XXX.
0. 4 .BXXXXX.XXXB.XXXXB...XXXXXXXBX.XXXXXXX?XX.XXXXXXX.?..XX?XXXXXXBXXX.?XXX..XXXX.
0. 5 .?BXXXXXXXXX.?XXXX.?.XXXXXXXB.B.XXXXXBXXXXBXXXX..X.XXXXXXXXXX?BXX.?.XX.X?.XXX.
0. 6 .?XXXXXXBXXXXBXXXB..BBXXXXXXB..?BXXXXXBXXXXXXXXX..XBXX?XXXXXXXBXXXB?.XX.?.XXX.
0. 7 .?XXXXXXBXXB.XXXXX..BXXXXXXXBX..XXXXXXXXXXXXXXX.XB.XXXXXXBXXXBXX.XX.XX.B..XXX.
0. 8 .XXXXXXXXXXBXXXXXX..XXXXXXXXXXB.BXXXXBXXX?XBXXXB.B.BXXXXXXXXX?BXBXXBXB....XXB.
0. 9 .?XXXXBXXXXB.?XXXB...XXXXXXXBX.BXXXXXXXXX.XXBXX.B..BXXXBXXXXBXXXXXB?XXX...XXX.
0.10 .XXXXX?.XXXBXBXXXB...XXXXXXXB.?.XXXXXBXXXXXXXXXX.X.XXXXXBXXXXXXXBXX.XX.X..XXX.
0.11 .BXXXXXXXXXBXBXXXB..XXXXXXXXXX.BXXXXXXXXX.XBXXXX..B.XXXXXXXXBXXXXXBX..X...XXX.
Good sectors: 195/936 (20%)
Missing sectors: 634/936 (67%)
Bad sectors: 107/936 (11%)
78 tracks, 1 heads, 12 sectors, 256 bytes per sector, 234 kB total
```

**Comment by davidgiven** [comment]
Potentially, but I've seen the vertical strip pattern before. There are 78 logical tracks, but you read 79, right?  So what I think's happening here is that the track spacing on the disk doesn't quite match that on the drive. Track 0 reads fine because the position matches, and reading physical track 79 works fine because it sees logical track 78, but the tracks in between are a mess.

Some of the tracks are pretty good --- could you look at the log and see which logical track it's finding on which physical track?

My suspicion is that the track spacing was wrong on the source drive. I don't know how, as I thought the spacing was fixed by the drive geometry. It's possible this is normal on Brother drives and, yes, that it used microspacing to find the tracks, but I didn't think that happened in the middle of the disk, instead only when trying to find track 0.

Sadly, I don't think there's anything I can do about this in software, as I suspect that doing anything about this would require modifying the drive.

**Comment by david-schmidt** [comment]
This log (and above track map) is actually from the older `fe-readbrother` code days - it seems to be a little "better" at finding good sectors on this horrible image than the newer converged source:
[Disk1.log](https://github.com/davidgiven/fluxengine/files/3390191/Disk1.log)

A good read using the latest `fluxengine read brother` on a perfectly good disk.  It seems that logical tracks trail physical tracks by two, consistent between my crappy (Disk1) and good (Disk3) images:
[Disk3.log](https://github.com/davidgiven/fluxengine/files/3390194/Disk3.log)

**Comment by davidgiven** [comment]
Yes, it's one out at the beginning of the disk, but two out at the end of the disk. That does look like a track spacing issue.

BTW, you might want to try `--bit-error-threshold=0.3` and see if that makes a difference. `--pulse-debounce-threshold` and `--clock-interval-bias` can also be changed (use `--help` to see the defaults), but I've very rarely found that they made much difference.

**Comment by david-schmidt** [comment]
Ah, nice tweaks.  I'm not getting any better results, so I agree with your assessment that we can't correct for this in software.  I am missing a 240k machine in my collection; so it's off to eBay I go.  I can do 120k and the later sort-of-DOS, but not in between.

Thanks for your help!

**Comment by davidgiven** [comment]
It'd be interesting to know whether a known-good 240kB machine can read these. I suspect those drives are a lot more interesting than they appear.

BTW, if you ever spot any program disks for the Brother machines (they made a few, of which I've seen a typing tutor and simple spreadsheet), please let me know --- I really want to get my hands on one.

**Comment by david-schmidt** [comment]
I'm looking at an auction now with "Spreadsheet, Punctuation Alert and Data Storage Disk" - will definitely be imaging anything I run across for you!
